# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: duolinguo robot application

on:
  push:
    branches:
      - main
  workflow_dispatch: # 手动触发
  schedule:
    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 18表示北京时间早上2点
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run duolinguo main procedure
        env:
          DUOLINGO_AUTH_TOKEN: ${{ secrets.DUOLINGO_AUTH_TOKEN }}
          BARK_AUTH_TOKEN: ${{ secrets.BARK_AUTH_TOKEN }}
        run: |
          python duolinguo-robot.py
      - name: Run heapdump main procedure
        env:
          HEAPDUMP_ACCOUNT: ${{ secrets.HEAPDUMP_ACCOUNT }}
          HEAPDUMP_PASSWD: ${{ secrets.HEAPDUMP_PASSWD }}
          BARK_AUTH_TOKEN: ${{ secrets.BARK_AUTH_TOKEN }}
        run: |
          python heapdump-robot.py

